// BR-01 — the official Ticket Number is generated by the backend and is unique.
// Format: TKT-<YYYY>-<6-digit zero-padded id>. Deriving it from the row's own
// autoincrement id inside the creating transaction (D-03) means it cannot
// collide; the unique constraint on Ticket.ticketNumber is the final guard.

export const TICKET_NUMBER_PATTERN = /^TKT-\d{4}-\d{6,}$/;

export function formatTicketNumber(year: number, id: number): string {
  return `TKT-${year}-${String(id).padStart(6, "0")}`;
}
